[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.run.save without any arguments is deprecated.Changes to attributes are automatically persisted.
I0205 11:14:56.611932 139731385550720 run.py:116] Using CLRS21 spec: {'train': {'num_samples': 1000, 'length': 16, 'seed': 1}, 'val': {'num_samples': 32, 'length': 64, 'seed': 2}, 'test': {'num_samples': 32, 'length': 64, 'seed': 3}}
I0205 11:14:59.498525 139731385550720 xla_bridge.py:231] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker:
2022-02-05 11:14:59.510395: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
I0205 11:14:59.510579 139731385550720 xla_bridge.py:231] Unable to initialize backend 'gpu': FAILED_PRECONDITION: No visible GPU devices.
I0205 11:14:59.511208 139731385550720 xla_bridge.py:231] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
W0205 11:14:59.511408 139731385550720 xla_bridge.py:235] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
manual >>  True
adj shape >>  (32, 20, 20)
manual >>  True
adj shape >>  (32, 20, 20)
manual >>  True
adj shape >>  (32, 20, 20)
manual >>  True
adj shape >>  (32, 20, 20)
manual >>  True
adj shape >>  (32, 20, 20)
I0205 11:15:30.094883 139731385550720 run.py:193] Compiled feedback step in 30.603182 s.
manual >>  True
adj shape >>  (32, 20, 20)
manual >>  True
adj shape >>  (32, 20, 20)
I0205 11:15:36.419462 139731385550720 run.py:207] (train) step 0: {'average_accuracy': 0.5287762380593263, 'average_shift': 3.15625}
manual >>  True
adj shape >>  (32, 80, 80)
manual >>  True
adj shape >>  (32, 80, 80)
I0205 11:15:54.276266 139731385550720 run.py:214] (val) step 0: {'average_accuracy': 0.5589673698239898, 'average_shift': 20.6875}
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/drive/MyDrive/Final Project/new_clrs/clrs/examples/run.py", line 305, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/content/drive/MyDrive/Final Project/new_clrs/clrs/examples/run.py", line 217, in main
    test_model_custom(model)
UnboundLocalError: local variable 'test_model_custom' referenced before assignment